services:
  database:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - path: ./backend/.env
        required: false
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_db

  backend:
    build: ./backend
    container_name: inclusion_backend
    env_file:
      - path: ./backend/.env
        required: false
    depends_on:
      - database
      - redis
    volumes:
      - media_data:/app/src/media

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - path: ./frontend/.env.production
        required: false
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  media_data:
