# Generated by Django 5.2.11 on 2026-02-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_created_at_content_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlikescontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.content'),
        ),
    ]
