# Generated by Django 5.2.11 on 2026-02-24 15:01

import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='avatars/test', upload_to='posts/', validators=[posts.validators.validate_post_file]),
            preserve_default=False,
        ),
    ]
