# Generated by Django 5.2.11 on 2026-02-25 09:36

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_description_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='posts/', validators=[common.validators.validate_media_file_extension, common.validators.validate_media_file_size]),
        ),
    ]
