# Generated by Django 5.2.11 on 2026-03-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_favoritepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoritePost',
        ),
    ]
