# Generated by Django 5.2.11 on 2026-02-19 17:33

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.webp', upload_to='avatars', validators=[authentication.validators.validate_avatar]),
        ),
    ]
