# Generated by Django 5.2.11 on 2026-03-03 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friend',
            constraint=models.CheckConstraint(condition=models.Q(('user1_id__lt', models.F('user2_id'))), name='user1_id_lt_user2_id'),
        ),
    ]
