# Generated by Django 5.2.11 on 2026-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_remove_friend_pk_remove_friendrequest_pk_friend_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friend',
            name='unique_friendship',
        ),
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_friend_request',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='id',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='friend',
            name='pk',
            field=models.CompositePrimaryKey('user1_id', 'user2_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='pk',
            field=models.CompositePrimaryKey('from_user_id', 'to_user_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
