# Generated by Django 5.2.11 on 2026-02-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_content_created_at_content_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.content')),
                ('lf_commentary', models.CharField(max_length=1000)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.longformcontent')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.content',),
        ),
    ]
