# Generated by Django 5.2.11 on 2026-02-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [

    ]
