# Generated by Django 5.2.11 on 2026-02-26 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_lf_commentary_comment_commentary_and_more'),
        ('content', '0002_content_created_at_content_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lf_commentary',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentary',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='lf_content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.longformcontent'),
            preserve_default=False,
        ),
    ]
