# Generated by Django 5.2.11 on 2026-02-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.CharField(default='hggh', max_length=100),
            preserve_default=False,
        ),
    ]
