# Generated by Django 5.2.11 on 2026-02-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storie',
            fields=[
                ('shortformcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.shortformcontent')),
            ],
            bases=('content.shortformcontent',),
        ),
    ]
