# Generated by Django 5.2.11 on 2026-02-24 19:00

import django.db.models.deletion
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_created_at_content_updated_at'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('shortformcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.shortformcontent')),
                ('file', models.FileField(upload_to='stories/', validators=[common.validators.validate_media_file_extension, common.validators.validate_media_file_size])),
            ],
            options={
                'abstract': False,
            },
            bases=('content.shortformcontent',),
        ),
        migrations.DeleteModel(
            name='Storie',
        ),
    ]
