/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainProfileRouteImport } from './routes/_main/profile'
import { Route as MainPostsRouteImport } from './routes/_main/posts'
import { Route as MainIncsRouteImport } from './routes/_main/incs'
import { Route as MainUsernameRouteImport } from './routes/_main/$username'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as MainStoriesIndexRouteImport } from './routes/_main/stories/index'
import { Route as MainPostsIndexRouteImport } from './routes/_main/posts/index'
import { Route as MainMessagesIndexRouteImport } from './routes/_main/messages/index'
import { Route as MainIncsIndexRouteImport } from './routes/_main/incs/index'
import { Route as MainStoriesIdRouteImport } from './routes/_main/stories/$id'
import { Route as MainPostsIdRouteImport } from './routes/_main/posts/$id'
import { Route as MainMessagesIdRouteImport } from './routes/_main/messages/$id'
import { Route as MainIncsIdRouteImport } from './routes/_main/incs/$id'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_auth.lazy').then((d) => d.Route))
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainPostsRoute = MainPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => MainRoute,
} as any)
const MainIncsRoute = MainIncsRouteImport.update({
  id: '/incs',
  path: '/incs',
  getParentRoute: () => MainRoute,
} as any)
const MainUsernameRoute = MainUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/$username.lazy').then((d) => d.Route),
)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-up.lazy').then((d) => d.Route))
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-in.lazy').then((d) => d.Route))
const MainStoriesIndexRoute = MainStoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => MainRoute,
} as any)
const MainPostsIndexRoute = MainPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainPostsRoute,
} as any)
const MainMessagesIndexRoute = MainMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => MainRoute,
} as any)
const MainIncsIndexRoute = MainIncsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainIncsRoute,
} as any)
const MainStoriesIdRoute = MainStoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/stories/$id.lazy').then((d) => d.Route),
)
const MainPostsIdRoute = MainPostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MainPostsRoute,
} as any).lazy(() =>
  import('./routes/_main/posts/$id.lazy').then((d) => d.Route),
)
const MainMessagesIdRoute = MainMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/messages/$id.lazy').then((d) => d.Route),
)
const MainIncsIdRoute = MainIncsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MainIncsRoute,
} as any).lazy(() =>
  import('./routes/_main/incs/$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$username': typeof MainUsernameRoute
  '/incs': typeof MainIncsRouteWithChildren
  '/posts': typeof MainPostsRouteWithChildren
  '/profile': typeof MainProfileRoute
  '/incs/$id': typeof MainIncsIdRoute
  '/messages/$id': typeof MainMessagesIdRoute
  '/posts/$id': typeof MainPostsIdRoute
  '/stories/$id': typeof MainStoriesIdRoute
  '/incs/': typeof MainIncsIndexRoute
  '/messages/': typeof MainMessagesIndexRoute
  '/posts/': typeof MainPostsIndexRoute
  '/stories/': typeof MainStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/$username': typeof MainUsernameRoute
  '/profile': typeof MainProfileRoute
  '/incs/$id': typeof MainIncsIdRoute
  '/messages/$id': typeof MainMessagesIdRoute
  '/posts/$id': typeof MainPostsIdRoute
  '/stories/$id': typeof MainStoriesIdRoute
  '/incs': typeof MainIncsIndexRoute
  '/messages': typeof MainMessagesIndexRoute
  '/posts': typeof MainPostsIndexRoute
  '/stories': typeof MainStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_main/$username': typeof MainUsernameRoute
  '/_main/incs': typeof MainIncsRouteWithChildren
  '/_main/posts': typeof MainPostsRouteWithChildren
  '/_main/profile': typeof MainProfileRoute
  '/_main/': typeof MainIndexRoute
  '/_main/incs/$id': typeof MainIncsIdRoute
  '/_main/messages/$id': typeof MainMessagesIdRoute
  '/_main/posts/$id': typeof MainPostsIdRoute
  '/_main/stories/$id': typeof MainStoriesIdRoute
  '/_main/incs/': typeof MainIncsIndexRoute
  '/_main/messages/': typeof MainMessagesIndexRoute
  '/_main/posts/': typeof MainPostsIndexRoute
  '/_main/stories/': typeof MainStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/$username'
    | '/incs'
    | '/posts'
    | '/profile'
    | '/incs/$id'
    | '/messages/$id'
    | '/posts/$id'
    | '/stories/$id'
    | '/incs/'
    | '/messages/'
    | '/posts/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/$username'
    | '/profile'
    | '/incs/$id'
    | '/messages/$id'
    | '/posts/$id'
    | '/stories/$id'
    | '/incs'
    | '/messages'
    | '/posts'
    | '/stories'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_main/$username'
    | '/_main/incs'
    | '/_main/posts'
    | '/_main/profile'
    | '/_main/'
    | '/_main/incs/$id'
    | '/_main/messages/$id'
    | '/_main/posts/$id'
    | '/_main/stories/$id'
    | '/_main/incs/'
    | '/_main/messages/'
    | '/_main/posts/'
    | '/_main/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/posts': {
      id: '/_main/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof MainPostsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/incs': {
      id: '/_main/incs'
      path: '/incs'
      fullPath: '/incs'
      preLoaderRoute: typeof MainIncsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$username': {
      id: '/_main/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof MainUsernameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/stories/': {
      id: '/_main/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof MainStoriesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/posts/': {
      id: '/_main/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof MainPostsIndexRouteImport
      parentRoute: typeof MainPostsRoute
    }
    '/_main/messages/': {
      id: '/_main/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MainMessagesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/incs/': {
      id: '/_main/incs/'
      path: '/'
      fullPath: '/incs/'
      preLoaderRoute: typeof MainIncsIndexRouteImport
      parentRoute: typeof MainIncsRoute
    }
    '/_main/stories/$id': {
      id: '/_main/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof MainStoriesIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/posts/$id': {
      id: '/_main/posts/$id'
      path: '/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof MainPostsIdRouteImport
      parentRoute: typeof MainPostsRoute
    }
    '/_main/messages/$id': {
      id: '/_main/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof MainMessagesIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/incs/$id': {
      id: '/_main/incs/$id'
      path: '/$id'
      fullPath: '/incs/$id'
      preLoaderRoute: typeof MainIncsIdRouteImport
      parentRoute: typeof MainIncsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainIncsRouteChildren {
  MainIncsIdRoute: typeof MainIncsIdRoute
  MainIncsIndexRoute: typeof MainIncsIndexRoute
}

const MainIncsRouteChildren: MainIncsRouteChildren = {
  MainIncsIdRoute: MainIncsIdRoute,
  MainIncsIndexRoute: MainIncsIndexRoute,
}

const MainIncsRouteWithChildren = MainIncsRoute._addFileChildren(
  MainIncsRouteChildren,
)

interface MainPostsRouteChildren {
  MainPostsIdRoute: typeof MainPostsIdRoute
  MainPostsIndexRoute: typeof MainPostsIndexRoute
}

const MainPostsRouteChildren: MainPostsRouteChildren = {
  MainPostsIdRoute: MainPostsIdRoute,
  MainPostsIndexRoute: MainPostsIndexRoute,
}

const MainPostsRouteWithChildren = MainPostsRoute._addFileChildren(
  MainPostsRouteChildren,
)

interface MainRouteChildren {
  MainUsernameRoute: typeof MainUsernameRoute
  MainIncsRoute: typeof MainIncsRouteWithChildren
  MainPostsRoute: typeof MainPostsRouteWithChildren
  MainProfileRoute: typeof MainProfileRoute
  MainIndexRoute: typeof MainIndexRoute
  MainMessagesIdRoute: typeof MainMessagesIdRoute
  MainStoriesIdRoute: typeof MainStoriesIdRoute
  MainMessagesIndexRoute: typeof MainMessagesIndexRoute
  MainStoriesIndexRoute: typeof MainStoriesIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainUsernameRoute: MainUsernameRoute,
  MainIncsRoute: MainIncsRouteWithChildren,
  MainPostsRoute: MainPostsRouteWithChildren,
  MainProfileRoute: MainProfileRoute,
  MainIndexRoute: MainIndexRoute,
  MainMessagesIdRoute: MainMessagesIdRoute,
  MainStoriesIdRoute: MainStoriesIdRoute,
  MainMessagesIndexRoute: MainMessagesIndexRoute,
  MainStoriesIndexRoute: MainStoriesIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
