// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "auth": {
    "sign-in": {
      "description": "Enter your email below to login to your account",
      "error": "Unable to sign in. Please try again.",
      "fields": {
        "password": {
          "label": "Password"
        },
        "username": {
          "label": "Username"
        }
      },
      "footer": {
        "link": "Sign up",
        "text": "Don't have an account?"
      },
      "submit_btn": "Sign In",
      "success": "Welcome back!",
      "title": "Login to your account"
    },
    "sign-out": {
      "error": "Unable to sign out. Please try again.",
      "success": "You’ve been signed out."
    },
    "sign-up": {
      "description": "Fill in the form below to create your account",
      "error": "Unable to create account. Please try again.",
      "fields": {
        "confirmPassword": {
          "label": "Confirm Password"
        },
        "email": {
          "label": "Email"
        },
        "firstName": {
          "label": "First Name"
        },
        "lastName": {
          "label": "Last Name"
        },
        "password": {
          "errors": {
            "missmatch": "Passwords do not match"
          },
          "label": "Password"
        },
        "username": {
          "errors": {
            "regex": "Letters, digits and @/./+/-/_ only"
          },
          "label": "Username"
        }
      },
      "footer": {
        "link": "Sign in",
        "text": "Already have an account?"
      },
      "submit_btn": "Create Account",
      "success": "Account created successfully.",
      "title": "Create your account"
    }
  },
  "comment": {
    "create": {
      "error": "Error while creating comment.",
      "success": "Comment created successfully!"
    },
    "delete": {
      "dialog": {
        "confirm": "Delete",
        "description": "This action cannot be undone.",
        "title": "Delete comment?",
        "trigger": "Delete comment"
      },
      "error": "Error while deleting comment.",
      "success": "Comment deleted successfully!"
    }
  },
  "common": {
    "actions": {
      "cancel": "Cancel",
      "confirm": "Confirm",
      "delete": "Delete",
      "deleting": "Deleting",
      "publish": "Publish",
      "publishing": "Publishing...",
      "save": "Save changes",
      "submit": "Submit",
      "update": "Update"
    },
    "confirm-dialog": {
      "cancel": "Cancel",
      "confirm": "Confirm",
      "description": "This action cannot be undone.",
      "title": "Are you sure?"
    },
    "create-content": {
      "description": "Select a content type below to continue.",
      "inc": {
        "description": "Share a quick thought or short update with your friends.",
        "label": "Create an inc"
      },
      "post": {
        "description": "Draft a new post, upload images, and share updates with your friends.",
        "label": "Create a post"
      },
      "story": {
        "description": "Share a moment that disappears after 24 hours.",
        "label": "Create a story"
      },
      "title": "Create new content"
    },
    "errors": {
      "mediaFileRequired": "Media file is required."
    }
  },
  "inc": {
    "create": {
      "error": "Error while creating inc.",
      "fields": {
        "content": {
          "placeholder": "What's new?"
        }
      },
      "success": "Inc created successfully!",
      "title": "Create new inc"
    },
    "delete": {
      "dialog": {
        "confirm": "Delete",
        "description": "This action cannot be undone.",
        "title": "Delete inc?",
        "trigger": "Delete inc"
      },
      "error": "Error while deleting inc.",
      "success": "Inc deleted successfully!"
    }
  },
  "note": {
    "create": {
      "default": "What are you thinking?",
      "error": "Error while upserting note.",
      "success": "Updated note successfully!"
    },
    "delete": {
      "error": "Error while deleting note.",
      "success": "Deleted note successfully!"
    },
    "edit": {
      "title": "Edit note"
    }
  },
  "post": {
    "create": {
      "dialog": {
        "description": {
          "placeholder": "What's new?"
        },
        "file": {
          "button": "Upload media"
        },
        "title": "Create new post"
      },
      "error": "Error while creating post.",
      "success": "Post created successfully!"
    },
    "delete": {
      "dialog": {
        "confirm": "Delete",
        "description": "This action cannot be undone.",
        "title": "Delete comment?",
        "trigger": "Delete comment"
      },
      "error": "Error while deleting post.",
      "success": "Post deleted successfully!"
    }
  }
}

export default Resources;
