// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "auth": {
    "sign-in": {
      "description": "Enter your email below to login to your account",
      "error": "Unable to sign in. Please try again.",
      "fields": {
        "password": {
          "label": "Password"
        },
        "username": {
          "label": "Username"
        }
      },
      "footer": {
        "link": "Sign up",
        "text": "Don't have an account?"
      },
      "submit_btn": "Sign In",
      "success": "Welcome back!",
      "title": "Login to your account"
    },
    "sign-out": {
      "error": "Unable to sign out. Please try again.",
      "success": "You’ve been signed out."
    },
    "sign-up": {
      "description": "Fill in the form below to create your account",
      "error": "Unable to create account. Please try again.",
      "fields": {
        "confirmPassword": {
          "label": "Confirm Password"
        },
        "email": {
          "label": "Email"
        },
        "firstName": {
          "label": "First Name"
        },
        "lastName": {
          "label": "Last Name"
        },
        "password": {
          "errors": {
            "missmatch": "Passwords do not match"
          },
          "label": "Password"
        },
        "username": {
          "errors": {
            "regex": "Letters, digits and @/./+/-/_ only"
          },
          "label": "Username"
        }
      },
      "footer": {
        "link": "Sign in",
        "text": "Already have an account?"
      },
      "submit_btn": "Create Account",
      "success": "Account created successfully.",
      "title": "Create your account"
    }
  },
  "chat-bot": {
    "ask": {
      "error": "Something went wrong while sending your request.",
      "loading": "The bot is thinking...",
      "success": "Response received successfully."
    }
  },
  "comment": {
    "create": {
      "error": "Error while creating comment.",
      "success": "Comment created successfully!"
    },
    "delete": {
      "dialog": {
        "confirm": "Delete",
        "description": "This action cannot be undone.",
        "title": "Delete comment?",
        "trigger": "Delete comment"
      },
      "error": "Error while deleting comment.",
      "success": "Comment deleted successfully!"
    },
    "empty": "There are no comments yet. Be the first!",
    "title": "Comments"
  },
  "common": {
    "actions": {
      "cancel": "Cancel",
      "close": "Close",
      "delete": "Delete",
      "deleting": "Deleting",
      "publish": "Publish",
      "publishing": "Publishing...",
      "remove": "Remove",
      "save": "Save",
      "saving": "Saving...",
      "submit": "Submit",
      "submitting": "Submitting",
      "update": "Update"
    },
    "confirm-dialog": {
      "cancel": "Cancel",
      "confirm": "Confirm",
      "description": "This action cannot be undone.",
      "title": "Are you sure?"
    },
    "createContent": {
      "description": "Select a content type below to continue.",
      "inc": {
        "description": "Share a quick thought or short update with your friends.",
        "label": "Create an inc"
      },
      "post": {
        "description": "Draft a new post, upload images, and share updates with your friends.",
        "label": "Create a post"
      },
      "story": {
        "description": "Share a moment that disappears after 24 hours.",
        "label": "Create a story"
      },
      "title": "Create new content"
    },
    "errors": {
      "file": {
        "empty": "The file cannot be empty.",
        "invalidFormat": "Supported formats: {{formats}}.",
        "required": "Please select a file.",
        "tooLarge": "Maximum file size - {{max}}."
      }
    },
    "friends": "Friends",
    "language": "Language",
    "mediaUploader": {
      "changeFile": "Change file",
      "fullscreen": "Fullscreen",
      "preview": "Preview",
      "select": "Click or drag and drop"
    },
    "notFound": {
      "button": "Back to Home",
      "description": "The page you are looking for does not exist or has been moved.",
      "title": "404 Not Found"
    },
    "notification": {
      "all": {
        "empty": "There is no notifications.",
        "title": "All"
      },
      "requests": {
        "empty": "There is no friend requests.",
        "title": "Requests"
      },
      "title": "Notifications"
    },
    "sideBar": {
      "chat-bot": "Chat Bot",
      "games": "Games",
      "incs": "Incs",
      "messages": "Messages",
      "newContent": "New Content",
      "posts": "Posts",
      "profile": "Profile",
      "settings": "Settings"
    },
    "theme": {
      "dark": "Dark",
      "light": "Light",
      "system": "System",
      "title": "Theme"
    },
    "time": {
      "justNow": "just now"
    }
  },
  "friend": {
    "request": {
      "accept": {
        "button": "Accept friend request",
        "error": "Error while accepting friend request.",
        "success": "Friend request successfully accepted."
      },
      "cancel": {
        "button": "Cancel friend request",
        "error": "Error while cancelling friend request.",
        "success": "Friend request successfully cancelled."
      },
      "decline": {
        "button": "Decline friend request",
        "error": "Error while declining friend request.",
        "success": "Friend request successfully declined."
      },
      "remove": {
        "button": "Remove friend",
        "error": "Error while removing friend.",
        "success": "Friend successfully removed."
      },
      "send": {
        "button": "Send friend request",
        "error": "Error while sending friend request.",
        "success": "Friend request successfully sent."
      }
    }
  },
  "games": {
    "best": "best",
    "current": "current",
    "emptyState": "emptyState",
    "games": {
      "title": "Games",
      "wordle": "Wordle",
      "wordleDescription": "Guess the word in 6 tries. After each guess, the color of the tiles will change to show how close your guess was to the word."
    },
    "hook": {
      "notEnoughLetters": "Not enough letters"
    },
    "wordle": {
      "comeBackTomorrow": "Come back tomorrow for a new word.",
      "error": "error",
      "loadingGame": "Loading game...",
      "title": "Wordle",
      "viewLeaderboard": "View Leaderboard",
      "winMessage": "winMessage"
    },
    "wordleLeaderboard": {
      "bestPlayers": "The best players based on their win streaks!",
      "loading": "Loading leaderboard...",
      "title": "Wordle Leaderboard"
    }
  },
  "inc": {
    "create": {
      "error": "Error while creating inc.",
      "fields": {
        "content": {
          "placeholder": "What's new?"
        }
      },
      "success": "Inc created successfully!",
      "title": "Create new inc"
    },
    "delete": {
      "dialog": {
        "confirm": "Delete",
        "description": "This action cannot be undone.",
        "title": "Delete inc?",
        "trigger": "Delete inc"
      },
      "error": "Error while deleting inc.",
      "success": "Inc deleted successfully!"
    }
  },
  "message": {
    "delete": {
      "dialog": {
        "confirm": "Delete",
        "description": "This action cannot be undone.",
        "title": "Delete message",
        "trigger": "Delete"
      },
      "error": "Failed to delete the message.",
      "success": "Message deleted successfully."
    },
    "send": {
      "error": "Failed to send the message.",
      "placeholder": "Type your message...",
      "success": "Message sent successfully.",
      "title": "New Message"
    },
    "title": "Messages",
    "update": {
      "error": "Error while updating message.",
      "fields": {
        "content": {
          "placeholder": "Type your message.."
        }
      },
      "success": "Message successfully updated.",
      "title": "Update message",
      "trigger": "Edit"
    }
  },
  "note": {
    "create": {
      "default": "What are you thinking?",
      "error": "Error while upserting note.",
      "success": "Updated note successfully!"
    },
    "delete": {
      "error": "Error while deleting note.",
      "success": "Deleted note successfully!"
    },
    "edit": {
      "title": "Edit note"
    }
  },
  "post": {
    "create": {
      "dialog": {
        "description": {
          "placeholder": "What's new?"
        },
        "file": {
          "button": "Upload media"
        },
        "title": "Create new post"
      },
      "error": "Error while creating post.",
      "success": "Post created successfully!"
    },
    "delete": {
      "dialog": {
        "confirm": "Delete",
        "description": "This action cannot be undone.",
        "title": "Delete post?",
        "trigger": "Delete post"
      },
      "error": "Error while deleting post.",
      "success": "Post deleted successfully!"
    }
  },
  "story": {
    "create": {
      "error": "Error while creating story.",
      "success": "Story created successfully!",
      "title": "Create story"
    },
    "delete": {
      "dialog": {
        "confirm": "Delete",
        "description": "This action cannot be undone.",
        "title": "Delete story?",
        "trigger": "Delete story"
      },
      "error": "Error while deleting story.",
      "success": "Story deleted successfully!"
    }
  },
  "user": {
    "avatar": {
      "error": "Error while updating avatar.",
      "form": {
        "description": "Update your avatar. This will be displayed on your profile.",
        "image": {
          "label": "Upload new photo",
          "size": "Recommended size is 256x256px. Max size 2MB."
        },
        "title": "Avatar"
      },
      "success": "Avatar updated successfully."
    },
    "biography": {
      "error": "Error while updating biography.",
      "success": "Biography updated successfully",
      "title": "Biography"
    },
    "fullName": {
      "error": "Error while updaing full name.",
      "form": {
        "firstName": "First Name",
        "lastName": "Last Name",
        "title": "Full Name"
      },
      "success": "Full name updated successfully"
    },
    "menu": {
      "profile": "Profile",
      "settings": "Settings",
      "signOut": "Sign Out"
    },
    "privacy": {
      "error": "Error while updating privacy settings",
      "form": {
        "description": "Choose if you want your profile to be public or private.",
        "isPrivate": {
          "description": "When private, only your friends can see your posts, incs... This setting protects your profile and personal content.",
          "title": "Private Account"
        },
        "title": "Account Visibility"
      },
      "success": "Account privacy updated successfully"
    },
    "settings": {
      "description": "Manage your account, security, and other information.",
      "general": "General",
      "personal": "Personal Information",
      "title": "Account settings"
    }
  }
}

export default Resources;
