# Generated by Django 5.2.11 on 2026-03-10 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordleResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('wordle', 'user', blank=True, editable=False, primary_key=True, serialize=False)),
                ('guesses', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure')], default='Failure', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wordle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordle.wordle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
