# Generated by Django 5.2.11 on 2026-03-10 12:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_wordleresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=150, unique=True)),
                ('length', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wordle',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wordleresult',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='failure', max_length=20),
        ),
        migrations.AlterField(
            model_name='wordleresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordleresult',
            name='wordle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='wordle.wordle'),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordles', to='wordle.word'),
        ),
    ]
