# Generated by Django 5.2.11 on 2026-03-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_word_wordle_date_alter_wordleresult_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='word',
            new_name='text',
        ),
    ]
